Error removed and name added
codex-team/workflow pull request #8
Opened 2021-02-20 13:57 UTC by robonetphy

resolve #7

2021-02-21 11:23 UTC, talyguryn requested changes

2021-02-21 11:23 UTC, talyguryn commented on .env.example
> +MENTION = "f0m41h4u7 specc nikmel2803 talyguryn GeekaN2 n0str neSpecc"
```suggestion
MENTION = "ilyamore88 fabled228 Xemka kebyo GeekaN2 ranemihir robonetphy neSpecc nikmel2803 talyguryn gohabereg khaydarov"
```

2021-02-21 11:23 UTC, talyguryn commented on .env.example
>  PR_TIME="0 9,18 * * 1-5"
```suggestion
PR_TIME="0 9,20 * * 1-5"
```

2021-02-21 11:23 UTC, talyguryn commented on src/index.js
>  const PR_TIME = process.env.PR_TIME || '0 9,18 * * 1-5';
```suggestion
const PR_TIME = process.env.PR_TIME || '0 9,20 * * 1-5';
```

2021-02-21 11:23 UTC, talyguryn commented on src/index.js
> +@specc @guryn @khaydarovm @nikmel2803 @xemk4
it would be great if this list will be created automatically by MENTION list may be

2021-02-21 11:23 UTC, talyguryn commented on src/index.js
> +  const meetingJob = new CronJob(MEETING_TIME, () => {
```suggestion

  const meetingJob = new CronJob(MEETING_TIME, () => {
```

2021-02-21 11:23 UTC, talyguryn commented on src/index.js
> +  'Europe/Moscow'
please add two spaces for lines 239-242

2021-02-21 11:23 UTC, talyguryn commented on src/index.js
> +  meetingJob.start();
```suggestion

  meetingJob.start();
```

2021-02-22 09:09 UTC, fabled228 approved these changes

2021-02-22 09:19 UTC, talyguryn approved these changes

2021-02-22 17:34 UTC, merged